### ISSUE TITLE
Add pack flush.

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/objects.pack#2]
I think title says it all :)

**Comment by csswizardry** [comment]
It’s flush by default :)

**Comment by nenadjelovac** [comment]
@csswizardry my bad. But how do you then have one with default gutters (and there is variable for that)?

**Comment by csswizardry** [comment]
I think I’ve had an idea… give me a few minutes :)

**Edit:** No I haven’t :(

**Comment by nenadjelovac** [comment]
@csswizardry yeah, other inuitcss modules don't have `*--default` (needs better naming probably) classes, but here it's kinda needed.

**Comment by csshugs** [comment]
@nenadjelovac want to take this issue over to the beta version?

**Comment by nenadjelovac** [comment]
@csshugs I'll move it there. Thnx.
