### ISSUE TITLE
Add pack--top?

### ISSUE THREAD

**Issue by albinekb** [inuitcss/objects.pack#3]
I think title says it all :)

**Comment by nenadjelovac** [comment]
Default vertical align is to the top, so no need for a modifier.

**Comment by albinekb** [comment]
@nenadjelovac but when i change to top i get a different result, i default is "baseline" ?

**Comment by nenadjelovac** [comment]
@albinekb do you have a live preview?

**Comment by csshugs** [comment]
[Demo](http://sassmeister.com/gist/6539cc77b76b7ad4f9f1)

**Comment by csshugs** [comment]
@nenadjelovac @albinekb I dont't see the need for a modifier neither

**Comment by albinekb** [comment]
Cool! I found the problem. Closing :) Thanks
